name: calcium continuous integration

on:
  push:
  pull_request:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - 
        name: Set up Rust
        uses: icepuma/rust-action@master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Run tests
        run: cargo test
