name: calcium continuous integration

on:
  push:
  pull_request:

env:
  IMAGE_NAME: docker-image

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -t $IMAGE_NAME --file=./Dockerfile .
      - name: Run tests
        run: docker run -i $IMAGE_NAME cargo test
